"""Draw the desk's system icons (GFX-107): notices, now, shortcuts, bin.

The app icons were generated by an image model (PROMPTS.md); these four
are drawn here instead, in the same family's style -- a diagonal gradient
with a soft light from the top, and one bold white glyph with a gentle
shade and a soft shadow -- so they can be regenerated without a model.
Each is drawn at 1024px and written as a 256px source next to the others;
`tools/art/icons.py` then masks and exports them like the rest.

    python3 tools/art/drawn_icons.py && python3 tools/art/icons.py
"""
import os
from PIL import Image, ImageDraw, ImageFilter, ImageChops

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
SRC = os.path.join(ROOT, "kernel_bootstrap", "assets", "icons", "src")
N = 1024


def gradient(top_left, bottom_right):
    """A diagonal gradient with a soft light from the top."""
    im = Image.new("RGB", (N, N))
    px = im.load()
    for y in range(N):
        for x in range(N):
            t = (x + y) / (2 * (N - 1))
            px[x, y] = tuple(int(a + (b - a) * t) for a, b in zip(top_left, bottom_right))
    light = Image.new("L", (N, N), 0)
    ImageDraw.Draw(light).ellipse((-N * 0.3, -N * 0.75, N * 1.3, N * 0.45), fill=70)
    light = light.filter(ImageFilter.GaussianBlur(N // 8))
    return Image.composite(Image.new("RGB", (N, N), (255, 255, 255)), im, light)


def glyph_onto(bg, mask, accent=None):
    """The white glyph `mask` over `bg`: a soft shadow under it, a gentle
    top-to-bottom shade on it. `accent` is (mask, colour) drawn on top."""
    shadow = mask.filter(ImageFilter.GaussianBlur(18)).point(lambda v: v * 0.35)
    shadow = ImageChops.offset(shadow, 0, 16)
    bg = Image.composite(Image.new("RGB", (N, N), (0, 0, 0)), bg, shadow)
    shade = Image.new("RGB", (N, N))
    d = ImageDraw.Draw(shade)
    for y in range(N):
        v = int(255 - 22 * y / N)
        d.line((0, y, N, y), fill=(v, v, min(255, v + 4)))
    bg = Image.composite(shade, bg, mask)
    if accent:
        amask, colour = accent
        bg = Image.composite(Image.new("RGB", (N, N), colour), bg, amask)
    return bg


def canvas():
    return Image.new("L", (N, N), 0)


def bell():
    m = canvas()
    d = ImageDraw.Draw(m)
    # The dome and flared skirt as one outline, the clapper under it.
    d.ellipse((352, 250, 672, 560), fill=255)
    d.polygon([(352, 420), (672, 420), (720, 700), (304, 700)], fill=255)
    d.rounded_rectangle((270, 660, 754, 730), radius=35, fill=255)
    d.ellipse((452, 730, 572, 830), fill=255)
    d.rounded_rectangle((482, 200, 542, 270), radius=30, fill=255)
    dot = canvas()
    ImageDraw.Draw(dot).ellipse((620, 220, 760, 360), fill=255)
    ring = canvas()
    ImageDraw.Draw(ring).ellipse((596, 196, 784, 384), fill=255)
    m = ImageChops.subtract(m, ring)
    return glyph_onto(gradient((99, 102, 241), (30, 41, 130)), m, (dot, (239, 68, 68)))


def gauge():
    m = canvas()
    d = ImageDraw.Draw(m)
    # A thick arc, three ticks, a needle to the upper right and its hub.
    d.pieslice((212, 262, 812, 862), 180, 360, fill=255)
    d.pieslice((302, 352, 722, 772), 180, 360, fill=0)
    d.rectangle((212, 562, 812, 900), fill=0)
    for a, b in [((282, 562), (342, 562)), ((512, 352), (512, 402)), ((682, 562), (742, 562))]:
        pass
    d.polygon([(492, 560), (532, 580), (720, 380), (700, 360)], fill=255)
    d.ellipse((452, 510, 572, 630), fill=255)
    return glyph_onto(gradient((34, 211, 238), (3, 105, 161)), m)


def keyboard():
    m = canvas()
    d = ImageDraw.Draw(m)
    d.rounded_rectangle((170, 330, 854, 700), radius=60, fill=255)
    hole = canvas()
    h = ImageDraw.Draw(hole)
    keys = []
    for row, (y, n, x0) in enumerate([(380, 8, 216), (470, 8, 216), (560, 1, 336)]):
        for i in range(n):
            if row == 2:
                box = (x0, y, 688, y + 70)
            else:
                box = (x0 + i * 76, y, x0 + i * 76 + 60, y + 70)
            h.rounded_rectangle(box, radius=14, fill=255)
            keys.append(box)
    m = ImageChops.subtract(m, hole)
    # The keys themselves, a little inset, white again; one in mint.
    k = canvas()
    kd = ImageDraw.Draw(k)
    for box in keys:
        kd.rounded_rectangle((box[0] + 6, box[1] + 6, box[2] - 6, box[3] - 6), radius=10, fill=235)
    m = ImageChops.lighter(m, k)
    mint = canvas()
    x = keys[5]
    ImageDraw.Draw(mint).rounded_rectangle((x[0] + 6, x[1] + 6, x[2] - 6, x[3] - 6), radius=10, fill=255)
    return glyph_onto(gradient((100, 116, 139), (30, 41, 59)), m, (mint, (52, 211, 153)))


def rubbish_bin():
    m = canvas()
    d = ImageDraw.Draw(m)
    d.rounded_rectangle((262, 270, 762, 350), radius=36, fill=255)
    d.rounded_rectangle((432, 210, 592, 290), radius=30, fill=255)
    d.polygon([(302, 380), (722, 380), (682, 820), (342, 820)], fill=255)
    d.rounded_rectangle((330, 780, 694, 840), radius=40, fill=255)
    grooves = canvas()
    g = ImageDraw.Draw(grooves)
    for x in (412, 512, 612):
        g.rounded_rectangle((x - 18, 450, x + 18, 750), radius=18, fill=255)
    m = ImageChops.subtract(m, grooves)
    return glyph_onto(gradient((248, 113, 113), (185, 28, 28)), m)


def globe():
    """The Web card's (WEB-001): a globe of meridians and parallels, with a
    mint orbit round it for the network."""
    m = canvas()
    d = ImageDraw.Draw(m)
    box = (232, 232, 792, 792)
    d.ellipse(box, fill=255)
    lines = canvas()
    ld = ImageDraw.Draw(lines)
    w = 34
    # Inside the disc: the rim's inner edge, two meridian arcs, the axis,
    # the equator and two parallels, cut out of the white.
    ld.ellipse((box[0] + w, box[1] + w, box[2] - w, box[3] - w), fill=255)
    m2 = ImageChops.subtract(m, lines)
    g = canvas()
    gd = ImageDraw.Draw(g)
    gd.ellipse((box[0], box[1], box[2], box[3]), outline=255, width=w)
    gd.ellipse((392, 232, 632, 792), outline=255, width=w)
    gd.rectangle((512 - w // 2, 232, 512 + w // 2, 792), fill=255)
    gd.rectangle((232, 512 - w // 2, 792, 512 + w // 2), fill=255)
    for y in (372, 652):
        half = int(((280 ** 2) - (y - 512) ** 2) ** 0.5)
        gd.rectangle((512 - half, y - w // 2, 512 + half, y + w // 2), fill=255)
    disc = canvas()
    ImageDraw.Draw(disc).ellipse(box, fill=255)
    m = ImageChops.lighter(m2, ImageChops.multiply(g, disc))
    orbit = canvas()
    od = ImageDraw.Draw(orbit)
    od.ellipse((150, 430, 874, 594), outline=255, width=26)
    od.ellipse((736, 404, 816, 484), fill=255)
    # The orbit passes behind the globe on its far side.
    behind = canvas()
    ImageDraw.Draw(behind).rectangle((0, 0, 1024, 512), fill=255)
    orbit = ImageChops.subtract(orbit, ImageChops.multiply(disc, behind))
    return glyph_onto(gradient((56, 189, 248), (29, 78, 216)), m, (orbit, (52, 211, 153)))


ICONS = {"notices": bell, "now": gauge, "shortcuts": keyboard, "bin": rubbish_bin, "web": globe}


def main():
    for name, draw in ICONS.items():
        im = draw().resize((256, 256), Image.LANCZOS)
        im.save(os.path.join(SRC, name + ".png"))
        print("drew", name)


if __name__ == "__main__":
    main()
